[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.networks.sepolia]
rpcUrl = "https://gateway.tenderly.co/public/sepolia"

[profile.default.networks.mumbai]
rpcUrl = "https://rpc.ankr.com/polygon_mumbai"

